from typing import List, Optional, Tuple

class KeywordProcessor:
    def __init__(self, case_sensitive: bool = False) -> None: ...
    def add_keyword(self, word: str, clean_name: Optional[str] = None) -> None: ...
    def remove_keyword(self, word: str) -> None: ...
    def extract_keywords(self, text: str, strategy: str = "all") -> List[str]: ...
    def extract_keywords_with_span(
        self, text: str, strategy: str = "all"
    ) -> List[Tuple[str, int, int]]: ...
    def get_all_keywords_with_clean_names(self) -> List[Tuple[str, str]]: ...
    def replace_keywords(self, text: str) -> str: ...
    def fuzzy_search(self, query: str, threshold: float = 0.8) -> List[Tuple[str, float]]: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
